### ISSUE TITLE
[v3] add exe generation

### ISSUE THREAD

**Issue by SebCanet** [satishsampath/wink-release#41]
Hi,
could it be possible to add exe file render? MP4 is great but still missing interactive feature (click button, hypertext, etc).
Many thanks for this reboot !

**Comment by satishsampath** [comment]
Click button, hypertext etc. are also available in this version. Instead of opening the MP4 directly, if you open the rendered .htm file present in the same folder as the MP4, you'll see that it works as expected.

**Comment by SebCanet** [comment]
Yes, but the EXE file was a very useful feature, without needing any browser and without testing each new version and verify if security option are still good for wink html generated files.
Thanks for explanation about html file.

**Comment by satishsampath** [comment]
EXE files are generally not considered good for distributing media these days, hence Wink 3.0 doesn't have this feature anymore. Even if we add an EXE feature now, it needs a browser-style rendering engine to play the video within the EXE file, so I'm going to leave this request closed.

**Comment by SebCanet** [comment]
I can understand, but after few months with my students it's more simple to send them an exe file besides many files.
It works well in Wink2, can't it be added with "at your own risk"?

**Comment by satishsampath** [comment]
A feature like this takes many weeks of work and the security risk I mentioned above (many email clients don't allow sending EXE files easily), so I'd like to see if it can be addressed in a better way first.
1) Who are your students?
2) Do you have a website where you can host the Wink output and send them a link, rather than sending files over email?
3) Would it be useful if Wink provided an upload-and-share functionality, so you can host the rendered tutorial in a Wink website and share the link?

**Comment by satishsampath** [comment]
Seb - want to email me directly so we can continue the discussion? satish -at- debugmode -dot- com
