### ISSUE TITLE
Wink2 & 3 project compatibility

### ISSUE THREAD

**Issue by SebCanet** [satishsampath/wink-release#58]
Hi,
I have a problem to open Wink3 project (wnk file) in WInk2 software, are they compatible?
If not, can we convert thel?
Thanks!

**Comment by satishsampath** [comment]
Wink supports backwards compatibility like other software, where the new version 3.0 can open files created by old versions. But the reverse isn't possible. The new version files have more information that the old version doesn't understand. I'd suggest installing Wink 3.0 and opening the file instead of trying to open via Wink 2.0

**Comment by satishsampath** [comment]
Can I know why you want to open a 3.0 file with Wink 2.0?

**Comment by SebCanet** [comment]
To compile in EXE file....

**Comment by satishsampath** [comment]
Can you please email me directly (satish -at- debugmode -dot- com)? Let's talk through it and I can try to help with your use case in a better way.
